### ISSUE TITLE
How can we do imputation using weighted knn? Could you please help?

### ISSUE THREAD

**Issue by alankritmishra** [kothari1997narayan/Knn_Imputation#1]

**Comment by kothari1997narayan** [comment]
Okay, so assume we want weighted KNN in terms of distance.
Like if you see sklearn Knn imputation function [https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html](url) , there are two options uniform or distance.
In this it weight points by the inverse of their distance..

So you can do something like this

```
> sort_indxs = dist[row].argsort()
> close_val = []
> total_dist = 0
> for i in sort_indxs:
>     if(np.isnan(data[i,col])):
>         continue
>     inv_dist = 1/dist[row,i]
>     total_dist = total_dist + inv_dist
>     close_val.append(data[i,col]*inv_dist)
>     if(len(close_val)==n_neighbors):
>         break
> adjusted_value = np.sum(close_val)/total_dist
> final_data[row][col] = adjusted_value
```


from [https://github.com/kothari1997narayan/Knn_Imputation/blob/8bfcc6a89e8e888421d76bbcd500e7c689ce7b00/knn_imputation.py#L82](url) you can change the above code..
What I am doing is I am weighing the points with the inverse distance so that the points which are closes given more importance, and then diving with the total weights
Something like 
`> (w1*x1 + w2*x2)/(w1+w2) 
`
where w's are the inverse of distance..
I hope this helps
